export const metadataBlocks = [
    "Wool",
    "Dirt",
    "Stone",
    "Wood",
    "Oak Sapling",
    "Sandstone",
    "Log",
    "Leaves",
    "Wooden Planks",
    "Stained Glass",
    "Stained Glass Pane",
    "Carpet",
    "Stained Clay",
    "Grass",
    "Stone Slab",
    "Stone Monster Egg",
    "Stone Bricks",
    "Wood Slab",
    "Anvil",
    "Block of Quartz",
    "Prismarine",
    "Red Sandstone",
    "Plant",
    "Dandelion",
    "Flower",
    "White Banner"
];

export const blockNamesArray = {
    'Wool\:0' : 'White Wool',
    'Wool\:1' : 'Orange Wool',
    'Wool\:2' : 'Magenta Wool',
    'Wool\:3' : 'Light Blue Wool',
    'Wool\:4' : 'Yellow Wool',
    'Wool\:5' : 'Lime Wool',
    'Wool\:6' : 'Pink Wool',
    'Wool\:7' : 'Gray Wool',
    'Wool\:8' : 'Light Gray Wool',
    'Wool\:9' : 'Cyan Wool',
    'Wool\:10' : 'Purple Wool',
    'Wool\:11' : 'Blue Wool',
    'Wool\:12' : 'Brown Wool',
    'Wool\:13' : 'Green Wool',
    'Wool\:14' : 'Red Wool',
    'Wool\:15' : 'Black Wool',
    "Stone\:0" : "Stone",
    "Stone\:1" : "Granite",
    "Stone\:2" : "Polished Granite",
    "Stone\:3" : "Diorite",
    "Stone\:4" : "Polished Diorite",
    "Stone\:5" : "Andesite",
    "Stone\:6" : "Polished Andesite",
    'Dirt\:0' : 'Dirt',
    'Dirt\:1' : 'Coarse Dirt',
    'Dirt\:2' : 'Podzol',
    'Wooden Planks\:0' : 'Oak Planks',
    'Wooden Planks\:1' : 'Spruce Planks',
    'Wooden Planks\:2' : 'Birch Planks',
    'Wooden Planks\:3' : 'Jungle Planks',
    'Wooden Planks\:4' : 'Acacia Planks',
    'Wooden Planks\:5' : 'Dark Oak Planks',
    'Oak Sapling\:0' : 'Oak Sapling',
    'Oak Sapling\:1' : 'Spruce Sapling',
    'Oak Sapling\:2' : 'Birch Sapling',
    'Oak Sapling\:3' : 'Jungle Sapling',
    'Oak Sapling\:4' : 'Acacia Sapling',
    'Oak Sapling\:5' : 'Dark Oak Sapling',
    'Sandstone\:0' : 'Sandstone',
    'Sandstone\:1' : 'Chiseled Sandstone',
    'Sandstone\:2' : 'Smooth Sandstone',
    'Leaves\:0' : 'Oak Leaves',
    'Leaves\:1' : 'Spruce Leaves',
    'Leaves\:2' : 'Birch Leaves',
    'Leaves\:3' : 'Jungle Leaves',
    'Stained Glass\:0' : 'White Stained Glass',
    'Stained Glass\:1' : 'Orange Stained Glass',
    'Stained Glass\:2' : 'Magenta Stained Glass',
    'Stained Glass\:3' : 'Light Blue Stained Glass',
    'Stained Glass\:4' : 'Yellow Stained Glass',
    'Stained Glass\:5' : 'Lime Stained Glass',
    'Stained Glass\:6' : 'Pink Stained Glass',
    'Stained Glass\:7' : 'Gray Stained Glass',
    'Stained Glass\:8' : 'Light Gray Stained Glass',
    'Stained Glass\:9' : 'Cyan Stained Glass',
    'Stained Glass\:10' : 'Purple Stained Glass',
    'Stained Glass\:11' : 'Blue Stained Glass',
    'Stained Glass\:12' : 'Brown Stained Glass',
    'Stained Glass\:13' : 'Green Stained Glass',
    'Stained Glass\:14' : 'Red Stained Glass',
    'Stained Glass\:15' : 'Black Stained Glass',
    'Stained Glass Pane\:0' : 'White Stained Glass Pane',
    'Stained Glass Pane\:1' : 'Orange Stained Glass Pane',
    'Stained Glass Pane\:2' : 'Magenta Stained Glass Pane',
    'Stained Glass Pane\:3' : 'Light Blue Stained Glass Pane',
    'Stained Glass Pane\:4' : 'Yellow Stained Glass Pane',
    'Stained Glass Pane\:5' : 'Lime Stained Glass Pane',
    'Stained Glass Pane\:6' : 'Pink Stained Glass Pane',
    'Stained Glass Pane\:7' : 'Gray Stained Glass Pane',
    'Stained Glass Pane\:8' : 'Light Gray Stained Glass Pane',
    'Stained Glass Pane\:9' : 'Cyan Stained Glass Pane',
    'Stained Glass Pane\:10' : 'Purple Stained Glass Pane',
    'Stained Glass Pane\:11' : 'Blue Stained Glass Pane',
    'Stained Glass Pane\:12' : 'Brown Stained Glass Pane',
    'Stained Glass Pane\:13' : 'Green Stained Glass Pane',
    'Stained Glass Pane\:14' : 'Red Stained Glass Pane',
    'Stained Glass Pane\:15' : 'Black Stained Glass Pane',
    'Carpet\:0' : 'White Carpet',
    'Carpet\:1' : 'Orange Carpet',
    'Carpet\:2' : 'Magenta Carpet',
    'Carpet\:3' : 'Light Blue Carpet',
    'Carpet\:4' : 'Yellow Carpet',
    'Carpet\:5' : 'Lime Carpet',
    'Carpet\:6' : 'Pink Carpet',
    'Carpet\:7' : 'Gray Carpet',
    'Carpet\:8' : 'Light Gray Carpet',
    'Carpet\:9' : 'Cyan Carpet',
    'Carpet\:10' : 'Purple Carpet',
    'Carpet\:11' : 'Blue Carpet',
    'Carpet\:12' : 'Brown Carpet',
    'Carpet\:13' : 'Green Carpet',
    'Carpet\:14' : 'Red Carpet',
    'Carpet\:15' : 'Black Carpet',
    'Stained Clay\:0' : 'White Terracotta',
    'Stained Clay\:1' : 'Orange Terracotta',
    'Stained Clay\:2' : 'Magenta Terracotta',
    'Stained Clay\:3' : 'Light Blue Terracotta',
    'Stained Clay\:4' : 'Yellow Terracotta',
    'Stained Clay\:5' : 'Lime Terracotta',
    'Stained Clay\:6' : 'Pink Terracotta',
    'Stained Clay\:7' : 'Gray Terracotta',
    'Stained Clay\:8' : 'Light Gray Terracotta',
    'Stained Clay\:9' : 'Cyan Terracotta',
    'Stained Clay\:10' : 'Purple Terracotta',
    'Stained Clay\:11' : 'Blue Terracotta',
    'Stained Clay\:12' : 'Brown Terracotta',
    'Stained Clay\:13' : 'Green Terracotta',
    'Stained Clay\:14' : 'Red Terracotta',
    'Stained Clay\:15' : 'Black Terracotta',
    'Stone Slab\:0' : 'Stone Slab',
    'Stone Slab\:1' : 'Sandstone Slab',
    'Stone Slab\:2' : 'Wooden Slab',
    'Stone Slab\:3' : 'Cobblestone Slab',
    'Stone Slab\:4' : 'Brick Slab',
    'Stone Slab\:5' : 'Stone Brick Slab',
    'Stone Slab\:6' : 'Quartz Slab',
    'Stone Slab\:7' : 'Nether Brick Slab',
    'Wood Slab\:0' : 'Oak Slab',
    'Wood Slab\:1' : 'Spruce Slab',
    'Wood Slab\:2' : 'Birch Slab',
    'Wood Slab\:3' : 'Jungle Slab',
    'Wood Slab\:4' : 'Acacia Slab',
    'Wood Slab\:5' : 'Dark Oak Slab',
    'Block of Quartz\:0' : 'Quartz Block',
    'Block of Quartz\:1' : 'Chiseled Quartz Block',
    'Block of Quartz\:2' : 'Quartz Pillar',
    'Prismarine\:0' : 'Prismarine',
    'Prismarine\:1' : 'Prismarine Bricks',
    'Prismarine\:2' : 'Dark Prismarine',
    'Red Sandstone\:0' : 'Red Sandstone',
    'Red Sandstone\:1' : 'Chiseled Red Sandstone',
    'Red Sandstone\:2' : 'Smooth Red Sandstone',
    'Plant\:0' : 'Dead Bush',
    'Plant\:1' : 'Grass',
    'Plant\:2' : 'Fern',
    'Flower\:0' : 'Poppy',
    'Flower\:1' : 'Blue Orchid',
    'Flower\:2' : 'Allium',
    'Flower\:3' : 'Azure Bluet',
    'Flower\:4' : 'Red Tulip',
    'Flower\:5' : 'Orange Tulip',
    'Flower\:6' : 'White Tulip',
    'Flower\:7' : 'Pink Tulip',
    'Flower\:8' : 'Oxeye Daisy',
    'Stone Monster Egg\:0' : 'Infested Stone',
    'Stone Monster Egg\:1' : 'Infested Cobblestone',
    'Stone Monster Egg\:2' : 'Infested Stone Brick',
    'Stone Monster Egg\:3' : 'Infested Mossy Stone Brick',
    'Stone Monster Egg\:4' : 'Infested Cracked Stone Brick',
    'Stone Monster Egg\:5' : 'Infested Chiseled Stone Brick',
    'Grass\:0' : 'Grass Block',
    'Anvil\:0' : 'Undamaged Anvil (north/south)',
    'Anvil\:1' : 'Undamaged Anvil (east/west)',
    'Anvil\:2' : 'Undamaged Anvil (north/south)',
    'Anvil\:3' : 'Undamaged Anvil (east/west)',
    'Anvil\:4' : 'Slightly Damaged Anvil (north/south)',
    'Anvil\:5' : 'Slightly Damaged Anvil (east/west)',
    'Anvil\:6' : 'Slightly Damaged Anvil (north/south)',
    'Anvil\:7' : 'Slightly Damaged Anvil (east/west)',
    'Anvil\:8' : 'Very Damaged Anvil (north/south)',
    'Anvil\:9' : 'Very Damaged Anvil (east/west)',
    'Anvil\:10' : 'Very Damaged Anvil (north/south)',
    'Anvil\:11' : 'Very Damaged Anvil (east/west)',
    'White Banner\:0' : 'White Banner (rotation 0)',
    'White Banner\:1' : 'White Banner (rotation 1)',
    'White Banner\:2' : 'White Banner (rotation 2)',
    'White Banner\:3' : 'White Banner (rotation 3)',
    'White Banner\:4' : 'White Banner (rotation 4)',
    'White Banner\:5' : 'White Banner (rotation 5)',
    'White Banner\:6' : 'White Banner (rotation 6)',
    'White Banner\:7' : 'White Banner (rotation 7)',
    'White Banner\:8' : 'White Banner (rotation 8)',
    'White Banner\:9' : 'White Banner (rotation 9)',
    'White Banner\:10' : 'White Banner (rotation 10)',
    'White Banner\:11' : 'White Banner (rotation 11)',
    'White Banner\:12' : 'White Banner (rotation 12)',
    'White Banner\:13' : 'White Banner (rotation 13)',
    'White Banner\:14' : 'White Banner (rotation 14)',
    'White Banner\:15' : 'White Banner (rotation 15)',
    'Wood\:0' : 'Oak Wood / Acacia Wood',
    'Wood\:1' : 'Spruce Wood / Dark Oak Wood',
    'Wood\:2' : 'Birch Wood / Acacia Wood',
    'Wood\:3' : 'Jungle Wood / Dark Oak Wood',
    'Wood\:4' : 'Oak Wood (rotated X) / Acacia Wood (rotated X)',
    'Wood\:5' : 'Spruce Wood (rotated X) / Dark Oak Wood (rotated X)',
    'Wood\:6' : 'Birch Wood (rotated X) / Acacia Wood (rotated X)',
    'Wood\:7' : 'Jungle Wood (rotated X) / Dark Oak Wood (rotated X)',
    'Wood\:8' : 'Oak Wood (rotated Z) / Acacia Wood (rotated Z)',
    'Wood\:9' : 'Spruce Wood (rotated Z) / Dark Oak Wood (rotated Z)',
    'Wood\:10' : 'Birch Wood (rotated Z) / Acacia Wood (rotated Z)',
    'Wood\:11' : 'Jungle Wood (rotated Z) / Dark Oak Wood (rotated Z)',
    'Wood\:12' : 'Oak Wood (bark) / Acacia Wood (bark)',
    'Wood\:13' : 'Spruce Wood (bark) / Dark Oak Wood (bark)',
    'Wood\:14' : 'Birch Wood (bark) / Acacia Wood (bark)',
    'Wood\:15' : 'Jungle Wood (bark) / Dark Oak Wood (bark)'
};